import crypto from "node:crypto";
import type {
  VaultPluginBlueprint,
  VaultPluginBuildTestPlan,
  VaultPluginDryRunPlan,
  VaultPluginGenerateRequest,
  VaultPluginGenerateResult,
  VaultPluginGeneratedFile,
  VaultPluginRequirements,
  VaultPluginRollbackPlan,
  VaultPluginSecurityReview,
  VaultPluginTemplate
} from "@security-portal/shared";
import {
  factoryExpansionReservedTargets,
  factoryExpansionTemplates,
  type FactoryCatalogTier,
  type FactoryExpansionTemplate
} from "./expansion-catalog";
import {
  githubPatRotationBackendFile,
  githubPatRotationBackendTestFile,
  githubPatRotationReadmeFile
} from "./github-pat-rotation-template";

const capturedAt = "2026-07-09";
const githubPopularityBasis = "GitHub Search API stars for Vault server plugins";

const coreVaultPluginTemplates: VaultPluginTemplate[] = [
  official("auth-kubernetes", "vault-plugin-auth-kubernetes", "auth", "Kubernetes Service Account authentication", "kubernetes"),
  official("auth-jwt", "vault-plugin-auth-jwt", "auth", "JWT and OIDC token authentication", "jwt"),
  official("auth-gcp", "vault-plugin-auth-gcp", "auth", "Google Cloud IAM and GCE authentication", "gcp"),
  learning("auth-plugin-example", "vault-auth-plugin-example", "auth", "Reference auth plugin implementation", "example-auth"),
  official("secrets-kv", "vault-plugin-secrets-kv", "secret", "KV secrets engine plugin reference", "custom-kv"),
  official("secrets-azure", "vault-plugin-secrets-azure", "secret", "Azure credentials broker", "azure"),
  official("secrets-gcp", "vault-plugin-secrets-gcp", "secret", "Google Cloud service account and IAM credential broker", "gcp"),
  official("secrets-ad", "vault-plugin-secrets-ad", "secret", "Active Directory account rotation and leasing", "ad"),
  official("secrets-openldap", "vault-plugin-secrets-openldap", "secret", "OpenLDAP credential lifecycle management", "openldap"),
  official("secrets-kubernetes", "vault-plugin-secrets-kubernetes", "secret", "Kubernetes Service Account credential broker", "kubernetes"),
  official("database-elasticsearch", "vault-plugin-database-elasticsearch", "database", "Dynamic Elasticsearch credentials", "elasticsearch"),
  official("database-redis", "vault-plugin-database-redis", "database", "Dynamic Redis credentials", "redis"),
  official("database-oracle", "vault-plugin-database-oracle", "database", "Dynamic Oracle credentials", "oracle"),
  official("database-snowflake", "vault-plugin-database-snowflake", "database", "Dynamic Snowflake credentials", "snowflake"),
  official("database-mongodbatlas", "vault-plugin-database-mongodbatlas", "database", "Dynamic MongoDB Atlas credentials", "mongodbatlas"),
  learning(
    "learn-secrets-hashicups",
    "learn-vault-plugin-secrets-hashicups",
    "secret",
    "HashiCups tutorial secrets engine scaffold",
    "hashicups"
  ),
  community(
    1,
    "community-venafi-pki",
    "Venafi/vault-pki-backend-venafi",
    "vault-pki-backend-venafi",
    "secret",
    58,
    "Venafi PKI certificate enrollment secrets engine",
    "venafi-pki"
  ),
  community(
    2,
    "community-u2f-auth",
    "bruj0/vault-plugin-auth-u2f",
    "vault-plugin-auth-u2f",
    "auth",
    53,
    "FIDO U2F human authentication method",
    "u2f"
  ),
  community(
    3,
    "community-slack-auth",
    "sethvargo/vault-auth-slack",
    "vault-auth-slack",
    "auth",
    50,
    "Slack identity based Vault authentication",
    "slack"
  ),
  community(
    4,
    "community-minio-secrets",
    "kula/vault-plugin-secrets-minio",
    "vault-plugin-secrets-minio",
    "secret",
    42,
    "MinIO user provisioning secrets engine",
    "minio"
  ),
  community(
    5,
    "community-spire-auth",
    "bloomberg/vault-auth-spire",
    "vault-auth-spire",
    "auth",
    42,
    "SPIRE SVID based Vault authentication",
    "spire"
  ),
  communityReference(
    "community-kafka-secrets",
    "Mongey/vault-plugin-secrets-kafka",
    "vault-plugin-secrets-kafka",
    "secret",
    29,
    "Apache Kafka client credential and ACL secrets engine",
    "kafka"
  )
];

export const vaultPluginTemplates = validateTemplateCatalog([
  ...coreVaultPluginTemplates,
  ...validateExpansionTargets(factoryExpansionTemplates).map(expansionTemplate)
]);

export function generateVaultPluginScaffold(request: VaultPluginGenerateRequest): VaultPluginGenerateResult {
  const template = findPluginTemplate(request.templateId);
  const pluginName = normalizePluginName(request.pluginName);
  const mountPath = normalizeMountPath(request.mountPath);
  const requirements = normalizeRequirements(request.requirements, template, mountPath);
  const version = normalizeVersion(request.version);
  const command = normalizeCommand(request.command);
  const description =
    request.description?.trim() || `${template.displayName} generated by the Security Portal Vault Plugin Factory`;
  const moduleName = `example.com/${pluginName}`;
  const generatedAt = new Date().toISOString();
  const files = buildFiles({
    template,
    pluginName,
    mountPath,
    version,
    command,
    description,
    moduleName,
    requirements
  });
  const scaffoldSha256 = hashFiles(files);
  const enableCommand =
    template.pluginType === "auth"
      ? `vault auth enable -path=${mountPath} ${pluginName}`
      : `vault secrets enable -path=${mountPath} ${pluginName}`;
  const commands = [
    "factory build start --isolated",
    "gofmt -w ./...",
    "go mod tidy",
    "go test ./...",
    "mkdir -p dist",
    `GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o dist/${command} ./cmd/${pluginName}`,
    `PLUGIN_SHA=$(sha256sum dist/${command} | awk '{print $1;}')`,
    `vault plugin register -command=${command} -sha256=$PLUGIN_SHA -version=${version} ${template.pluginType} ${pluginName}`,
    enableCommand
  ];
  const applyPlan = [
    "Verify Vault health, plugin_directory, api_addr, and the least-privilege plugin AppRole.",
    "Compile and test the confirmed specification in the isolated Factory CodeBuild runner.",
    `Copy dist/${command} to the Vault plugin_directory on every Vault node.`,
    `Register ${pluginName} in the ${template.pluginType} plugin catalog with the binary SHA256.`,
    `Enable ${pluginName} at ${mountPath}/ using the registered version ${version}.`,
    "Run a mount/read smoke test and capture the plugin version and running SHA256."
  ];
  const warnings = [
    "The scaffold SHA is for generated source review only; real Vault registration requires the compiled binary SHA256.",
    "Apply is safe in mock mode. Real mode requires the binary to already exist under Vault's plugin_directory.",
    template.pluginType === "auth"
      ? "Auth plugins require sudo capability on sys/auth and should be promoted through approval."
      : "Secrets and database plugins require create/update capability on sys/mounts and catalog registration."
  ];
  if (template.integrationTarget === "github-pat") {
    warnings.push(
      "GitHub does not expose a public API to create PATs; this plugin validates and rotates an operator-supplied PAT.",
      "Automated retirement revokes a fine-grained PAT's organization access only; classic PATs require manual revocation."
    );
  }

  return {
    id: crypto.randomUUID(),
    template,
    pluginName,
    mountPath,
    version,
    command,
    description,
    generatedAt,
    scaffoldSha256,
    files,
    commands,
    applyPlan,
    warnings,
    requirements,
    blueprint: buildBlueprint({ template, pluginName, mountPath, version, command, description, requirements }),
    dryRun: buildDryRunPlan({ template, pluginName, mountPath, version, command }),
    buildTest: buildBuildTestPlan({ template, pluginName, command, files }),
    rollbackPlan: buildRollbackPlan({ template, pluginName, mountPath, version }),
    securityReview: buildSecurityReview({ template, files, warnings })
  };
}

export function findPluginTemplate(templateId: string): VaultPluginTemplate {
  const template = vaultPluginTemplates.find((item) => item.id === templateId);
  if (!template) {
    throw new Error(`Unknown Vault plugin template: ${templateId}`);
  }
  return template;
}

function expansionTemplate(template: FactoryExpansionTemplate): VaultPluginTemplate {
  return baseTemplate({
    id: template.id,
    name: template.name,
    displayName: template.displayName,
    pluginType: template.pluginType,
    source: template.source,
    repository: template.repository,
    sourceUrl: template.sourceUrl ?? `https://github.com/${template.repository}`,
    description: template.description,
    target: template.target,
    buildProfile: "reference",
    aliases: template.aliases,
    catalogTier: template.catalogTier,
    catalogExpansion: true
  });
}

function validateTemplateCatalog(templates: VaultPluginTemplate[]): VaultPluginTemplate[] {
  for (const field of ["id", "name"] as const) {
    const seen = new Set<string>();
    for (const template of templates) {
      const value = template[field].toLowerCase();
      if (seen.has(value)) {
        throw new Error(`Duplicate Vault plugin template ${field}: ${template[field]}`);
      }
      seen.add(value);
    }
  }
  return templates;
}

function validateExpansionTargets(templates: FactoryExpansionTemplate[]): FactoryExpansionTemplate[] {
  const reservedTargets = new Set<string>(factoryExpansionReservedTargets);
  for (const template of templates) {
    if (reservedTargets.has(template.target)) {
      throw new Error(`Reserved Vault or portal integration target in catalog expansion: ${template.target}`);
    }
  }
  return templates;
}

function official(
  id: string,
  name: string,
  pluginType: VaultPluginTemplate["pluginType"],
  description: string,
  target: string
): VaultPluginTemplate {
  return baseTemplate({
    id,
    name,
    pluginType,
    source: "official",
    repository: `hashicorp/${name}`,
    sourceUrl: `https://github.com/hashicorp/${name}`,
    description,
    target,
    buildProfile: "adapter"
  });
}

function learning(
  id: string,
  name: string,
  pluginType: VaultPluginTemplate["pluginType"],
  description: string,
  target: string
): VaultPluginTemplate {
  const repository =
    name === "learn-vault-plugin-secrets-hashicups"
      ? `hashicorp-education/${name}`
      : `hashicorp/${name}`;
  return baseTemplate({
    id,
    name,
    pluginType,
    source: "learning",
    repository,
    sourceUrl: `https://github.com/${repository}`,
    description,
    target,
    buildProfile: "scaffold"
  });
}

function community(
  rank: number,
  id: string,
  repository: string,
  name: string,
  pluginType: VaultPluginTemplate["pluginType"],
  stars: number,
  description: string,
  target: string
): VaultPluginTemplate {
  return baseTemplate({
    id,
    name,
    pluginType,
    source: "community",
    repository,
    sourceUrl: `https://github.com/${repository}`,
    description,
    target,
    buildProfile: "reference",
    popularity: {
      stars,
      rank,
      capturedAt,
      basis: githubPopularityBasis
    }
  });
}

function communityReference(
  id: string,
  repository: string,
  name: string,
  pluginType: VaultPluginTemplate["pluginType"],
  stars: number,
  description: string,
  target: string
): VaultPluginTemplate {
  return baseTemplate({
    id,
    name,
    pluginType,
    source: "community",
    repository,
    sourceUrl: `https://github.com/${repository}`,
    description,
    target,
    buildProfile: "reference",
    popularity: {
      stars,
      capturedAt,
      basis: "GitHub repository stars for a community Kafka Vault plugin"
    }
  });
}

function baseTemplate({
  id,
  name,
  displayName,
  pluginType,
  source,
  repository,
  sourceUrl,
  description,
  target,
  buildProfile,
  popularity,
  aliases = [],
  catalogTier,
  catalogExpansion = false
}: {
  id: string;
  name: string;
  displayName?: string;
  pluginType: VaultPluginTemplate["pluginType"];
  source: VaultPluginTemplate["source"];
  repository: string;
  sourceUrl: string;
  description: string;
  target: string;
  buildProfile: VaultPluginTemplate["buildProfile"];
  popularity?: VaultPluginTemplate["popularity"];
  aliases?: string[];
  catalogTier?: FactoryCatalogTier;
  catalogExpansion?: boolean;
}): VaultPluginTemplate {
  const typePrefix = pluginType === "secret" ? "secrets" : pluginType;
  return {
    id,
    name,
    displayName: displayName ?? name,
    pluginType,
    source,
    repository,
    sourceUrl,
    description,
    defaultMountPath: `${target}`,
    defaultCommand: name,
    defaultVersion: "v0.1.0",
    integrationTarget: target,
    buildProfile,
    popularity,
    tags: [
      pluginType,
      source,
      target,
      typePrefix,
      ...aliases,
      ...(catalogTier ? [catalogTier] : []),
      ...(catalogExpansion ? ["catalog expansion"] : []),
      ...(popularity?.rank ? ["community top 5"] : []),
      ...(source === "learning" ? ["tutorial"] : [])
    ],
    guardrails: guardrailsFor(pluginType, target),
    marketplace: marketplaceFor({ pluginType, source, target, popularity, catalogTier })
  };
}

function marketplaceFor({
  pluginType,
  source,
  target,
  popularity,
  catalogTier
}: {
  pluginType: VaultPluginTemplate["pluginType"];
  source: VaultPluginTemplate["source"];
  target: string;
  popularity?: VaultPluginTemplate["popularity"];
  catalogTier?: FactoryCatalogTier;
}): VaultPluginTemplate["marketplace"] {
  const maturity =
    catalogTier === "conditional"
      ? "conditional"
      : catalogTier === "lab"
        ? "lab-only"
        : source === "official"
      ? "production-ready"
      : source === "learning"
        ? "learning"
        : catalogTier === "priority" || popularity?.rank
          ? "reference"
          : "experimental";
  const riskLevel =
    catalogTier === "lab" ? "high" : pluginType === "auth" || source === "community" || source === "partner" ? "medium" : "low";
  return {
    maturity,
    riskLevel,
    recommendedUse:
      catalogTier === "priority"
        ? `Prioritize ${target} for compatibility, revocation, and release-artifact validation before rollout.`
        : catalogTier === "conditional"
          ? `Use ${target} only after environment-specific API and Vault compatibility checks pass.`
          : catalogTier === "lab"
            ? `Keep ${target} in build and test workflows until maintenance, compatibility, and revocation checks pass.`
            : source === "learning"
        ? `Use ${target} as a tutorial or prototype starter before hardening it.`
        : source === "community" || source === "partner"
          ? `Use ${target} as a reviewed community reference and run a security review before production.`
          : `Use ${target} as the standard starting point for a controlled Vault plugin rollout.`,
    lastReviewedAt: capturedAt,
    badges: [
      source,
      pluginType,
      maturity,
      riskLevel === "low" ? "low risk" : "review required",
      ...(catalogTier ? [catalogTier] : []),
      ...(popularity?.rank ? [`top ${popularity.rank}`] : [])
    ]
  };
}

function guardrailsFor(pluginType: VaultPluginTemplate["pluginType"], target: string): string[] {
  if (target === "github-pat") {
    return [
      "Accept newly created PATs only through a write-only rotation request and never log or echo them.",
      "Restrict creds/* reads to the intended workload with a dedicated least-privilege Vault policy.",
      "Treat fine-grained PAT organization-access revocation and classic PAT manual revocation as separate controls."
    ];
  }
  if (pluginType === "auth") {
    return [
      "Require sudo-gated approval before sys/auth enable.",
      "Constrain identity alias metadata and default policies.",
      "Add lockout and token TTL tuning before production."
    ];
  }
  if (pluginType === "database") {
    return [
      "Use least-privilege admin credentials for credential rotation.",
      "Test revoke statements against ephemeral users.",
      "Set max TTL lower than the backing database password policy window."
    ];
  }
  return [
    "Keep upstream API tokens out of generated source and audit logs.",
    "Implement renew/revoke paths before production use.",
    "Set plugin-specific environment variables in the catalog, not app code."
  ];
}

function buildBlueprint({
  template,
  pluginName,
  mountPath,
  version,
  command,
  description,
  requirements
}: {
  template: VaultPluginTemplate;
  pluginName: string;
  mountPath: string;
  version: string;
  command: string;
  description: string;
  requirements: VaultPluginRequirements;
}): VaultPluginBlueprint {
  return {
    id: `blueprint-${pluginName}`,
    name: `${pluginName} standard rollout`,
    summary: `${template.displayName} blueprint for ${mountPath}/ at ${version}`,
    defaults: {
      mountPath,
      ttl: requirements.ttl,
      rotation: requirements.rotationStrategy,
      environment: requirements.environment
    },
    questions: [
      {
        id: "plugin-intent",
        question: "What is the business purpose of this plugin?",
        answer: description,
        required: true
      },
      {
        id: "mount-path",
        question: "Which Vault path should be enabled?",
        answer: `${mountPath}/`,
        required: true
      },
      {
        id: "runtime-command",
        question: "Which binary command will Vault run?",
        answer: command,
        required: true
      },
      {
        id: "rotation",
        question: "What lifecycle behavior must be completed before production?",
        answer: `${requirements.rotationStrategy}; revoke: ${requirements.revokeStrategy}`,
        required: true
      },
      {
        id: "promotion",
        question: "Which environment should receive this first?",
        answer: "dev, then staging, then production after approval",
        required: true
      }
    ]
  };
}

function buildDryRunPlan({
  template,
  pluginName,
  mountPath,
  version,
  command
}: {
  template: VaultPluginTemplate;
  pluginName: string;
  mountPath: string;
  version: string;
  command: string;
}): VaultPluginDryRunPlan {
  const mountTarget = template.pluginType === "auth" ? `sys/auth/${mountPath}` : `sys/mounts/${mountPath}`;
  return {
    mode: "dry-run",
    summary: `Dry-run will register ${pluginName}, enable ${mountPath}/, and verify the running plugin version before promotion.`,
    changes: [
      {
        action: "verify",
        target: "sys/health",
        before: "unknown Vault health",
        after: "healthy Vault cluster required",
        risk: "low"
      },
      {
        action: "create",
        target: `sys/plugins/catalog/${template.pluginType}/${pluginName}`,
        before: "plugin not registered by Factory",
        after: `${command} registered at ${version} with compiled binary SHA256`,
        risk: isExternalTemplate(template) ? template.marketplace.riskLevel : "low"
      },
      {
        action: "create",
        target: mountTarget,
        before: `${mountPath}/ is not managed by this Factory run`,
        after: `${pluginName} enabled at ${mountPath}/`,
        risk: template.pluginType === "auth" ? "high" : "medium"
      },
      {
        action: "verify",
        target: template.pluginType === "auth" ? "sys/auth" : "sys/mounts",
        before: "mount state unverified",
        after: `running_plugin_version should equal ${version}`,
        risk: "low"
      }
    ],
    collisions: [
      `Block apply if ${mountPath}/ already exists with a different plugin type.`,
      `Block apply if catalog entry ${pluginName} exists with a different command or SHA256.`
    ],
    approvals: [
      "Require vault-admin role for any apply.",
      template.pluginType === "auth"
        ? "Require security approver sign-off before enabling auth methods."
        : "Require service owner approval before production mount creation."
    ]
  };
}

function buildBuildTestPlan({
  template,
  pluginName,
  command,
  files
}: {
  template: VaultPluginTemplate;
  pluginName: string;
  command: string;
  files: VaultPluginGeneratedFile[];
}): VaultPluginBuildTestPlan {
  return {
    status: "warn",
    steps: [
      {
        label: "Dependency tidy",
        command: "go mod tidy",
        status: "pending",
        durationMs: 0,
        detail: "Waiting for the isolated CodeBuild runner."
      },
      {
        label: "Unit tests",
        command: "go test ./...",
        status: "pending",
        durationMs: 0,
        detail: "Generated unit tests have not run yet."
      },
      {
        label: "Plugin binary",
        command: `go build -o dist/${command} ./cmd/${pluginName}`,
        status: "pending",
        durationMs: 0,
        detail: `${files.length} generated files will be compiled for linux/arm64.`
      },
      {
        label: "Binary checksum",
        command: `sha256sum dist/${command}`,
        status: "pending",
        durationMs: 0,
        detail: "Run this against the compiled binary before real Vault registration."
      }
    ]
  };
}

function buildRollbackPlan({
  template,
  pluginName,
  mountPath,
  version
}: {
  template: VaultPluginTemplate;
  pluginName: string;
  mountPath: string;
  version: string;
}): VaultPluginRollbackPlan {
  const disableCommand =
    template.pluginType === "auth" ? `vault auth disable ${mountPath}` : `vault secrets disable ${mountPath}`;
  return {
    available: true,
    summary: `Rollback disables ${mountPath}/ and optionally removes ${pluginName} ${version} from the plugin catalog after traffic is drained.`,
    commands: [
      `vault read sys/plugins/catalog/${template.pluginType}/${pluginName}`,
      disableCommand,
      `vault plugin deregister -version=${version} ${template.pluginType} ${pluginName}`
    ],
    steps: [
      {
        label: "Drain usage",
        detail: "Confirm no active clients, tokens, leases, or renewals depend on the mount.",
        destructive: false
      },
      {
        label: "Disable mount",
        detail:
          template.pluginType === "auth"
            ? `Disable auth method at auth/${mountPath}.`
            : `Disable secrets mount at ${mountPath}/.`,
        destructive: true
      },
      {
        label: "Deregister catalog entry",
        detail: `Remove ${pluginName} ${version} only after all Vault nodes no longer need the binary.`,
        destructive: true
      }
    ]
  };
}

function buildSecurityReview({
  template,
  files,
  warnings
}: {
  template: VaultPluginTemplate;
  files: VaultPluginGeneratedFile[];
  warnings: string[];
}): VaultPluginSecurityReview {
  const findings: VaultPluginSecurityReview["findings"] = [
    {
      severity: isExternalTemplate(template) ? template.marketplace.riskLevel : "low",
      title: "External dependency review",
      detail:
        isExternalTemplate(template)
          ? "Partner and community plugin references should be pinned, reviewed, and tested before production."
          : "Official or learning source is used as a scaffold, but dependencies still need pin review.",
      remediation: "Run dependency review, license review, and reproducible build verification."
    },
    {
      severity: template.pluginType === "auth" ? "high" : "medium",
      title: "Vault capability boundary",
      detail: warnings[warnings.length - 1] ?? "Plugin rollout requires privileged Vault paths.",
      remediation: "Use least-privilege policy and route production apply through approval."
    },
    {
      severity: files.some((file) => /token|secret|password/i.test(file.content)) ? "medium" : "low",
      title: "Generated source secret handling",
      detail: "Generated scaffold avoids hardcoded secret values, but integration callbacks still need validation.",
      remediation: "Keep credentials in Vault configuration or environment variables and redact logs."
    }
  ];
  const highCount = findings.filter((finding) => finding.severity === "high").length;
  const mediumCount = findings.filter((finding) => finding.severity === "medium").length;
  const score = Math.max(55, 100 - highCount * 18 - mediumCount * 9);
  return {
    score,
    posture: highCount > 0 ? "needs-review" : mediumCount > 1 ? "needs-review" : "ready",
    findings
  };
}

function isExternalTemplate(template: VaultPluginTemplate): boolean {
  return template.source === "community" || template.source === "partner";
}

function buildFiles({
  template,
  pluginName,
  mountPath,
  version,
  command,
  description,
  moduleName,
  requirements
}: {
  template: VaultPluginTemplate;
  pluginName: string;
  mountPath: string;
  version: string;
  command: string;
  description: string;
  moduleName: string;
  requirements: VaultPluginRequirements;
}): VaultPluginGeneratedFile[] {
  const factoryName = template.pluginType === "auth" ? "AuthFactory" : "BackendFactory";
  const isGithubPatRotation = template.integrationTarget === "github-pat";
  return [
    {
      path: "go.mod",
      language: "go",
      content: `module ${moduleName}

go 1.22

require (
	github.com/hashicorp/vault/api v1.15.0
	github.com/hashicorp/vault/sdk v0.15.0
)
`
    },
    {
      path: `cmd/${pluginName}/main.go`,
      language: "go",
      content: `package main

import (
	"context"
	"log"
	"os"

	"github.com/hashicorp/vault/api"
	"github.com/hashicorp/vault/sdk/logical"
	vaultplugin "github.com/hashicorp/vault/sdk/plugin"

	generated "${moduleName}/internal/plugin"
)

func main() {
	apiClientMeta := &api.PluginAPIClientMeta{}
	flags := apiClientMeta.FlagSet()
	if err := flags.Parse(os.Args[1:]); err != nil {
		log.Fatal(err)
	}

	tlsConfig := apiClientMeta.GetTLSConfig()
	tlsProvider := api.VaultPluginTLSProvider(tlsConfig)

	if err := vaultplugin.Serve(&vaultplugin.ServeOpts{
		BackendFactoryFunc: func(ctx context.Context, conf *logical.BackendConfig) (logical.Backend, error) {
			backend, err := generated.${factoryName}(ctx, conf)
			if err != nil {
				return nil, err
			}
			return backend, nil
		},
		TLSProviderFunc: tlsProvider,
	}); err != nil {
		log.Fatal(err)
	}
}
`
    },
    {
      path: "internal/plugin/backend.go",
      language: "go",
      content: isGithubPatRotation
        ? githubPatRotationBackendFile(pluginName)
        : backendFile(template, pluginName, requirements)
    },
    {
      path: "internal/plugin/backend_test.go",
      language: "go",
      content: isGithubPatRotation
        ? githubPatRotationBackendTestFile()
        : `package plugin

import (
	"context"
	"testing"
)

func TestReadStatus(t *testing.T) {
	response, err := readStatus(context.Background(), nil, nil)
	if err != nil {
		t.Fatalf("readStatus returned an error: %v", err)
	}
	if response == nil || response.Data["status"] != "generated" {
		t.Fatalf("unexpected response: %#v", response)
	}
}
`
    },
    {
      path: "README.md",
      language: "markdown",
      content: isGithubPatRotation
        ? githubPatRotationReadmeFile({
            template,
            pluginName,
            mountPath,
            version,
            command,
            description,
            requirements
          })
        : `# ${pluginName}

${description}

Generated from \`${template.repository}\` as a ${template.pluginType} plugin starter.

## Confirmed requirements

- Target system: ${requirements.targetSystem}
- Authentication: ${requirements.authMethod}
- API path: ${requirements.apiBasePath}
- TTL: ${requirements.ttl}
- Rotation: ${requirements.rotationStrategy}
- Revoke: ${requirements.revokeStrategy}
- Mount: ${requirements.mountPath}/
- First environment: ${requirements.environment}

## Build

\`\`\`bash
go mod tidy
go test ./...
mkdir -p dist
GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o dist/${command} ./cmd/${pluginName}
PLUGIN_SHA=$(sha256sum dist/${command} | awk '{print $1;}')
\`\`\`

## Register and enable

\`\`\`bash
vault plugin register -command=${command} -sha256=$PLUGIN_SHA -version=${version} ${template.pluginType} ${pluginName}
${template.pluginType === "auth" ? "vault auth" : "vault secrets"} enable -path=${mountPath} ${pluginName}
\`\`\`

## Production guardrails

${template.guardrails.map((guardrail) => `- ${guardrail}`).join("\n")}
`
    },
    {
      path: "factory/requirements.json",
      language: "json",
      content: `${JSON.stringify(requirements, null, 2)}\n`
    },
    {
      path: "vault/apply.hcl",
      language: "hcl",
      content: `# Policy fragment for controlled plugin rollout.
path "sys/plugins/catalog/${template.pluginType}/${pluginName}" {
  capabilities = ["create", "update", "read"]
}

path "sys/${template.pluginType === "auth" ? "auth" : "mounts"}/${mountPath}" {
  capabilities = ["create", "update", "read", "sudo"]
}
`
    },
    {
      path: "Makefile",
      language: "makefile",
      content: `.PHONY: test build sha

PLUGIN=${command}

test:
	go test ./...

build:
	mkdir -p dist
	go build -o dist/$(PLUGIN) ./cmd/${pluginName}

sha: build
	sha256sum dist/$(PLUGIN)
`
    }
  ];
}

function backendFile(
  template: VaultPluginTemplate,
  pluginName: string,
  requirements: VaultPluginRequirements
): string {
  const pathName = template.pluginType === "auth" ? "login" : "config";
  return `package plugin

import (
	"context"

	"github.com/hashicorp/vault/sdk/framework"
	"github.com/hashicorp/vault/sdk/logical"
)

func BackendFactory(ctx context.Context, conf *logical.BackendConfig) (logical.Backend, error) {
	backend := &framework.Backend{
		Help: "${pluginName} generated plugin scaffold",
		PathsSpecial: &logical.Paths{
			SealWrapStorage: []string{"config"},
		},
		Paths: []*framework.Path{
			{
				Pattern: "${pathName}",
				Callbacks: map[logical.Operation]framework.OperationFunc{
					logical.ReadOperation: readStatus,
				},
				HelpSynopsis: "Read generated plugin scaffold status.",
			},
		},
		BackendType: logical.Type${template.pluginType === "auth" ? "Credential" : "Logical"},
	}
	if err := backend.Setup(ctx, conf); err != nil {
		return nil, err
	}
	return backend, nil
}

func AuthFactory(ctx context.Context, conf *logical.BackendConfig) (logical.Backend, error) {
	return BackendFactory(ctx, conf)
}

func readStatus(_ context.Context, _ *logical.Request, _ *framework.FieldData) (*logical.Response, error) {
	return &logical.Response{
		Data: map[string]interface{}{
			"status": "generated",
			"target_system": ${JSON.stringify(requirements.targetSystem)},
			"api_base_path": ${JSON.stringify(requirements.apiBasePath)},
			"ttl": ${JSON.stringify(requirements.ttl)},
			"rotation": ${JSON.stringify(requirements.rotationStrategy)},
			"revoke": ${JSON.stringify(requirements.revokeStrategy)},
			"next": "replace scaffold callbacks with ${template.integrationTarget} integration logic",
		},
	}, nil
}
`;
}

function normalizeRequirements(
  value: VaultPluginRequirements | undefined,
  template: VaultPluginTemplate,
  mountPath: string
): VaultPluginRequirements {
  const fallback: VaultPluginRequirements = {
    targetSystem: template.integrationTarget,
    authMethod: "configuration credential",
    apiBasePath: "not specified",
    ttl: template.pluginType === "auth" ? "1h" : template.pluginType === "database" ? "30m" : "15m",
    rotationStrategy: "manual review required",
    revokeStrategy: "manual review required",
    mountPath,
    environment: "dev",
    confirmed: false
  };
  if (!value) return fallback;
  const normalizedMount = normalizeMountPath(value.mountPath);
  if (normalizedMount !== mountPath) throw new Error("Confirmed requirement mount path does not match the generation request");
  return {
    ...value,
    targetSystem: value.targetSystem.trim(),
    authMethod: value.authMethod.trim(),
    apiBasePath: value.apiBasePath.trim(),
    ttl: value.ttl.trim(),
    rotationStrategy: value.rotationStrategy.trim(),
    revokeStrategy: value.revokeStrategy.trim(),
    mountPath: normalizedMount
  };
}

function hashFiles(files: VaultPluginGeneratedFile[]): string {
  const hash = crypto.createHash("sha256");
  for (const file of files) {
    hash.update(file.path);
    hash.update("\0");
    hash.update(file.content);
    hash.update("\0");
  }
  return hash.digest("hex");
}

function normalizePluginName(value: string): string {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  if (!normalized) {
    throw new Error("Plugin name is required");
  }
  return normalized;
}

function normalizeMountPath(value: string): string {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/^\/+|\/+$/g, "")
    .replace(/[^a-z0-9/_-]/g, "-")
    .replace(/\/+/g, "/");
  if (!normalized) {
    throw new Error("Mount path is required");
  }
  return normalized;
}

function normalizeVersion(value: string): string {
  const version = value.trim();
  if (!/^v\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(version)) {
    throw new Error("Version must be a semantic version such as v0.1.0");
  }
  return version;
}

function normalizeCommand(value: string): string {
  const command = value
    .trim()
    .replace(/[^A-Za-z0-9._-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  if (!command) {
    throw new Error("Plugin command is required");
  }
  return command;
}
